version: '3.8'

services:
  ml_fastapi_production:
    image: jafarijason/ml_fastapi_production:1.0.4
    networks:
      - traefik-public
    deploy:
      mode: replicated
      restart_policy:
          condition: any
      placement:
        constraints:
          - node.platform.os == linux
      replicas: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.ml_fastapi_production-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.ml_fastapi_production-http.entrypoints=http
        - traefik.http.routers.ml_fastapi_production-http.middlewares=https-redirect
        - traefik.http.routers.ml_fastapi_production-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.ml_fastapi_production-https.entrypoints=https
        - traefik.http.routers.ml_fastapi_production-https.tls=true
        - traefik.http.routers.ml_fastapi_production-https.tls.certresolver=le
        - traefik.http.services.ml_fastapi_production.loadbalancer.server.port=8000
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first




networks:
  traefik-public:
    external: true